### ISSUE TITLE
 "Week 8 ready for review"

### ISSUE THREAD

**Issue by Han434** [Han434/week8Exe#1]
@pawaitemadisoncollege Week 8 is complete.

**Comment by pawaitemadisoncollege** [comment]
Hi @Han434! This work shows a good start with consuming a restful api with javacode.

A few things to keep in mind if/when you do this type of work in a real program:

- [x] This code would generally be placed in a DAO for easier reuse. https://github.com/Han434/week8Exe/blob/ca1007d585848989d4ae22e5ae08945281ae0217/src/test/java/TestServiceClient.java#L18-L24  To improve flexibility, the method containing this code would receive a parameter for the pet id and return the Pet object. 
- [x] Also, the endpoint would generally be placed in a properties file so that it is easy to update without a source code change. https://github.com/Han434/week8Exe/blob/ca1007d585848989d4ae22e5ae08945281ae0217/src/test/java/TestServiceClient.java#L20
